# Generated by Django 5.0.3 on 2024-03-30 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0002_alter_language_managers"),
        ("translate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="source_language",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_language",
                to="languages.language",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="translation",
            name="target_language",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_language",
                to="languages.language",
            ),
            preserve_default=False,
        ),
    ]
