# Generated by Django 5.0.3 on 2024-04-05 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("languages", "0002_alter_language_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "translator",
                    models.CharField(
                        choices=[
                            ("amazon", "Amazon"),
                            ("deelp", "Deepl"),
                            ("google", "Goolge"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "processor",
                    models.CharField(
                        choices=[("amazon", "Amazon"), ("google", "Google")],
                        max_length=255,
                    ),
                ),
                (
                    "source_lang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_lang",
                        to="languages.language",
                    ),
                ),
                (
                    "target_lang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_lang",
                        to="languages.language",
                    ),
                ),
            ],
        ),
    ]
