# Generated by Django 5.0.3 on 2024-04-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preferences", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preferences",
            name="translator",
            field=models.CharField(
                choices=[
                    ("amazon", "Amazon"),
                    ("deepl", "Deepl"),
                    ("google", "Goolge"),
                ],
                max_length=255,
            ),
        ),
    ]
