# Generated by Django 5.0.3 on 2024-04-05 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0002_alter_language_managers"),
        ("nlp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="textpiece",
            name="language",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="language",
                to="languages.language",
            ),
            preserve_default=False,
        ),
    ]
