name: Django Tests CI
on: [pull_request, push]
jobs:
  excute_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: python manage.py test
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GOOGLE_CLOUD_CRED_FILE_NAME: ${{ secrets.GOOGLE_CLOUD_CRED_FILE_NAME }}
          GOOGLE_CLOUD_SCOPES: ${{ secrets.GOOGLE_CLOUD_SCOPES }}
